# Generated by Django 2.2.5 on 2019-10-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0007_auto_20191014_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerregistration',
            name='emailid',
            field=models.EmailField(max_length=254),
        ),
    ]
