# Generated by Django 2.2.5 on 2019-10-14 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0008_auto_20191014_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerregistration',
            name='emailid',
        ),
    ]
