# Generated by Django 2.2.5 on 2019-10-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0009_remove_farmerregistration_emailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerregistration',
            name='emailid',
            field=models.EmailField(default='k@gmail.com', max_length=254),
        ),
    ]
