# Generated by Django 2.2.5 on 2019-10-14 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0010_farmerregistration_emailid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerregistration',
            old_name='emailid',
            new_name='mailid',
        ),
    ]
