# Generated by Django 2.2.5 on 2019-11-21 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0012_auto_20191014_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineerregister',
            name='University',
        ),
    ]
