# Generated by Django 2.2.5 on 2019-11-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0013_remove_engineerregister_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='cropregistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('area', models.IntegerField()),
                ('soil', models.CharField(max_length=50)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('irrigation', models.CharField(max_length=50)),
                ('farming', models.CharField(max_length=50)),
            ],
        ),
    ]
