# Generated by Django 2.2.5 on 2019-11-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0015_auto_20191122_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmerquiries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.TextField()),
                ('quiry', models.CharField(max_length=50)),
                ('fileup', models.FileField(upload_to='images/')),
            ],
        ),
    ]
