# Generated by Django 2.2.5 on 2019-12-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0016_farmerquiries'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname1', models.CharField(max_length=50)),
                ('sname', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('qstn', models.CharField(max_length=50)),
            ],
        ),
    ]
