# Generated by Django 2.2.5 on 2019-12-09 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0017_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fname1',
            new_name='fname',
        ),
    ]
