# Generated by Django 2.2.5 on 2019-12-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0018_auto_20191209_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='fname',
        ),
        migrations.AddField(
            model_name='contact',
            name='firstname',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
