# Generated by Django 2.2.5 on 2019-12-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0019_auto_20191210_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='typesofcrops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cropname', models.CharField(max_length=50)),
            ],
        ),
    ]
