# Generated by Django 2.2.5 on 2019-12-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0020_typesofcrops'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropregistration',
            name='user',
            field=models.CharField(default='local', max_length=40),
        ),
    ]
