# Generated by Django 2.2.5 on 2019-12-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0021_cropregistration_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='typesofcrops',
            name='time',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='typesofcrops',
            name='cropname',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
