# Generated by Django 2.2.5 on 2019-12-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0022_auto_20191212_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='typesofcrops',
            name='soil',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
