# Generated by Django 2.2.5 on 2019-12-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0023_typesofcrops_soil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typesofcrops',
            name='cropname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='typesofcrops',
            name='soil',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='typesofcrops',
            name='time',
            field=models.IntegerField(default=''),
        ),
    ]
