# Generated by Django 2.2.5 on 2019-12-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0025_auto_20191212_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typesofcrops',
            old_name='cropname',
            new_name='name',
        ),
    ]
