# Generated by Django 2.2.5 on 2019-12-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0026_auto_20191212_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerquiries',
            name='status',
            field=models.CharField(default='hghj', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmerquiries',
            name='fid',
            field=models.EmailField(max_length=254),
        ),
    ]
